document.addEventListener('DOMContentLoaded', function () { const menuToggle = document.querySelector('.menu-toggle'); const nav = document.querySelector('nav'); menuToggle.addEventListener('click', function () { nav.classList.toggle('active') }) }); document.addEventListener('DOMContentLoaded', function () { init() }); async function init() { try { const main = document.querySelector("main"); const toggleButtons = createToggleButtons(); main.appendChild(toggleButtons); const displayContainer = document.createElement("article"); displayContainer.style.minHeight = "400px"; main.appendChild(displayContainer); displayContainer.classList.add("grid"); setupToggleView(displayContainer); const members = await fetchMembers(); displayMembers(members, displayContainer) } catch (error) { console.error("Error durante la inicialización:", error) } }
async function fetchMembers() {
    try {
        const cached = sessionStorage.getItem("membersData"); if (cached) { return JSON.parse(cached) }
        const response = await fetch("data/members.json"); if (!response.ok) { throw new Error("Error en la respuesta de la red") }
        const membersData = await response.json(); sessionStorage.setItem("membersData", JSON.stringify(membersData)); return membersData
    } catch (error) { console.error("Error fetching members:", error); return [] }
}
function createToggleButtons() { const btnContainer = document.createElement("div"); btnContainer.className = "menu"; const gridButton = document.createElement("button"); gridButton.id = "grid"; gridButton.textContent = "Grid View"; const listButton = document.createElement("button"); listButton.id = "list"; listButton.textContent = "List View"; btnContainer.appendChild(gridButton); btnContainer.appendChild(listButton); return btnContainer }
function createMemberCard(member) { const sectionEl = document.createElement("section"); const img = document.createElement("img"); img.src = `images/${member.image}`; img.alt = member.name; img.setAttribute("width", "16"); img.setAttribute("height", "16"); const h2 = document.createElement("h2"); h2.textContent = member.name; const address = document.createElement("p"); address.textContent = member.address; const phone = document.createElement("p"); phone.textContent = member.phone; const websiteLink = document.createElement("a"); websiteLink.href = member.website; websiteLink.textContent = "Visitar sitio"; const email = document.createElement("p"); email.textContent = member.email; const description = document.createElement("p"); description.textContent = member.description; sectionEl.appendChild(img); sectionEl.appendChild(h2); sectionEl.appendChild(address); sectionEl.appendChild(phone); sectionEl.appendChild(websiteLink); sectionEl.appendChild(email); sectionEl.appendChild(description); return sectionEl }
function displayMembers(members, container) { container.innerHTML = ""; members.forEach((member) => { const card = createMemberCard(member); container.appendChild(card) }) }
function setupToggleView(displayContainer) { const gridButton = document.querySelector("#grid"); const listButton = document.querySelector("#list"); gridButton.addEventListener("click", () => { displayContainer.classList.add("grid"); displayContainer.classList.remove("list") }); listButton.addEventListener("click", () => { displayContainer.classList.add("list"); displayContainer.classList.remove("grid") }) }
document.addEventListener('DOMContentLoaded', function () { const launchYearEl = document.getElementById('launchYear'); const lastModifiedEl = document.getElementById('lastModified'); if (launchYearEl && lastModifiedEl) { launchYearEl.textContent = new Date().getFullYear(); lastModifiedEl.textContent = document.lastModified } })


